ARG NODE_IMAGE=node:24.15.0-alpine
ARG PORT=3000






# Stage 1: Base runtime
FROM ${NODE_IMAGE} AS base

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install locked dependencies for the build
RUN npm ci

# Copy source files
COPY . .

# Expose the application port
EXPOSE ${PORT}






# Stage 2: build runtime (only for production builds)
FROM base AS builder

# Copy Config
COPY next.config.ts /app/next.config.ts

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Build the Next.js application
RUN npm run build






# Stage 3: dev runtime
FROM base AS dev

# Start the application in dev mode
CMD ["npm", "run", "dev"]







# Stage 4: Production runtime
FROM ${NODE_IMAGE} AS production

WORKDIR /app

# Set production environment
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Cloud Run uses the PORT environment variable
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create a non-root user
RUN addgroup -S myGroup
RUN adduser -S myUser -G myGroup

# Copy application files
COPY --from=builder --chown=myUser:myGroup /app/package.json ./
COPY --from=builder --chown=myUser:myGroup /app/package-lock.json ./
COPY --from=builder --chown=myUser:myGroup /app/node_modules ./node_modules
COPY --from=builder --chown=myUser:myGroup /app/.next ./.next
COPY --from=builder --chown=myUser:myGroup /app/public ./public
COPY --from=builder --chown=myUser:myGroup /app/next.config.ts ./next.config.ts

USER myUser

# Expose the application port
EXPOSE ${PORT}

# Start Next.js production server
CMD ["npm", "run", "start"]