ARG NODE_IMAGE=node:24.15.0-alpine
ARG PORT=8080






# Stage 1: Base runtime
FROM ${NODE_IMAGE} AS base

WORKDIR /app

# FOR SIGIL Error
ENV NODE_OPTIONS="--max-old-space-size=512"

# Copy package files first for dependency caching
COPY package.json package-lock.json ./

# Install all dependencies including devDependencies (needed for TypeScript compilation)
RUN npm ci

# Copy source code and configuration
COPY tsconfig.json tsconfig.build.json nest-cli.json ./
COPY src/ ./src/

# Expose the application port
EXPOSE ${PORT}







# Stage 2: build runtime (only for production builds)
FROM base AS builder

# Build the NestJS application
RUN npm run build







# Stage 3: dev runtime
FROM base AS dev

# Start the application
CMD ["npm", "run", "start:dev"]








# Stage 4: Production runtime
FROM ${NODE_IMAGE} AS production

# # Remove devDependencies after build
# RUN npm prune --omit=dev

# Install security updates
# RUN apk update && apk upgrade --no-cache

WORKDIR /app

# Create a non-root user
RUN addgroup -S myGroup
RUN adduser -S myUser -G myGroup

# Copy only what we need from the builder
COPY --from=builder --chown=myUser:myGroup /app/node_modules ./node_modules
COPY --from=builder --chown=myUser:myGroup /app/dist ./dist
COPY --from=builder --chown=myUser:myGroup /app/package.json ./

# Switch to non-root user
USER myUser

# Expose the application port
EXPOSE ${PORT}

# Set production environment
ENV NODE_ENV=production
ENV NODE_OPTIONS="--max-old-space-size=512"
# ENV PORT=8080

# Start the application
CMD ["node", "dist/main.js"]