name: "eternal-frame-backend"

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - eternal_frame_network

  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    env_file: ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - backend_pgadmin_data:/var/lib/pgadmin
    networks:
      - eternal_frame_network

  database:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    networks:
      - eternal_frame_network

  backend:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    depends_on:
      rabbitmq:
        condition: service_healthy 
    env_file: ./.env
    volumes:
      - ./.:/app
      - /app/node_modules
    networks:
      - eternal_frame_network

volumes:
  backend_postgres_data: {}
  backend_pgadmin_data: {}

networks:
  eternal_frame_network:
    driver: bridge